### ISSUE TITLE
Epilogos track occasionally drags behind other tracks on pan event 

### ISSUE THREAD

**Issue by alexpreynolds** [higlass/higlass-multivec#41] opened 2020-06-13 19:33 UTC
**Issue**

I observe an issue with higlass-multivec pan events, where the epilogos/stacked-bar track will occasionally not align correctly with the other tracks. 

Pieces of the track will either disappear and/or be shifted horizontally, taking them out of alignment with other tracks.

A subsequent pan or zoom event by the user seems to "reset" the view, bringing the track back into alignment.

Here is an animation showing the effect:

![multivecTest mov](https://user-images.githubusercontent.com/33584/84577451-07ae6200-ad71-11ea-8ef1-2be805f09722.gif)

The red peak is shifted to the right, upstream of where it should be, leaving a gap upstream. A subsequent pan event redraws the tiles and positions them correctly.

**Observed**

This is observed on a local test site running the current versions of higlass/higlass-multivec 1.9.5/0.2.4. I also observe this issue when bringing the test viewconf into higlass.io.

**Input**

Here is a link to a test viewconf:

https://gist.github.com/alexpreynolds/2e3c3be9fa8784a27070469d4acef558

I believe this might be a regression from an older (pre-0.2.0) version of higlass-multivec. Unfortunately, I was not able to find any commit that references this or a potential fix.

**Comment by pkerpedjiev** [comment] 2020-06-14 20:17
This was caused by the new async rerender mechanism for auto-scaling quantitative tracks. Should be fixed in v0.2.5.

**Closed by pkerpedjiev** 2020-06-14 20:17 UTC

**Comment by alexpreynolds** [comment] 2020-06-16 23:36
Just confirming that the issue no longer appears to occur. Many thanks!!
